In [ ]:
divvy_in = read.csv('/content/df_ts_in_1721_full.csv')
divvy_out = read.csv('/content/df_ts_out_1721_full.csv')
community = read.csv('/content/Divvy_stations_community.csv')
divvy_inout_cluster = read.csv('/content/divvy_inout_cluster.csv')

In [ ]:
library(stringr)
community$station_name1 <- str_replace_all(community$station_name,' ','.')
community$station_name1 <- str_replace_all(community$station_name1,'&','.')
head(community$station_name1)

[1] "Buckingham.Fountain"         "Shedd.Aquarium"
[3] "Burnham.Harbor"              "State.St...Harrison.St"
[5] "Dusable.Harbor"              "Field.Blvd...South.Water.St"

In [ ]:
tail(lapply(divvy_in,function(x) { length(which(is.na(x)))}))

$Halsted.St...35th.St....
[1] 1

$Manor.Ave...Leland.Ave
[1] 1

$Broadway...Belmont.Ave
[1] 1

$Cannon.Dr...Fullerton.Ave
[1] 1

$Logan.Blvd...Elston.Ave
[1] 1

$Kosciuszko.Park
[1] 1

In [ ]:
tail(lapply(divvy_out,function(x) { length(which(is.na(x)))}))

$Halsted.St...35th.St....
[1] 1

$Manor.Ave...Leland.Ave
[1] 1

$Broadway...Belmont.Ave
[1] 1

$Cannon.Dr...Fullerton.Ave
[1] 1

$Logan.Blvd...Elston.Ave
[1] 1

$Kosciuszko.Park
[1] 1

In [ ]:
# install.packages('imputeTS')
library(imputeTS)
divvy_in <- na_interpolation(divvy_in)
divvy_out <- na_interpolation(divvy_out)

Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo

In [ ]:
# TRANSPOSE

# first remember the names
timestamp_divin <- divvy_in$time_stamp
timestamp_divout <- divvy_out$time_stamp

# transpose all but the first column (name)
divvy_in.tfull <- as.data.frame(t(divvy_in[,-1]))
colnames(divvy_in.tfull) <- timestamp_divin
head(divvy_in.tfull)

divvy_out.tfull <- as.data.frame(t(divvy_out[,-1]))
colnames(divvy_out.tfull) <- timestamp_divout
head(divvy_out.tfull)

                          2017-01-01 00:20:00 2017-01-01 00:30:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 00:40:00 2017-01-01 00:50:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 01:00:00 2017-01-01 01:10:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 01:20:00 2017-01-01 01:30:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 01:40:00 2017-01-01 01:50:00 ⋯
Keeler.Ave...Roosevelt.Rd 0                   0                   ⋯
East.End.Ave...87th.St    0                   0                   ⋯
NA.                       0                   0                   ⋯
Greenwood.Ave...91st.St   0                   0                   ⋯
Big.Marsh.Park            0                   0                   ⋯
Kildare.Ave...26th.St     0                   0                   ⋯
                          2018-09-15 22:00:00 2018-09-15 22:10:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 22:20:00 2018-09-15 22:30:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 22:40:00 2018-09-15 22:50:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 23:00:00 2018-09-15 23:10:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 23:20:00 2018-09-15 23:30:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0

                          2017-01-01 00:20:00 2017-01-01 00:30:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 00:40:00 2017-01-01 00:50:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 01:00:00 2017-01-01 01:10:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 01:20:00 2017-01-01 01:30:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 01:40:00 2017-01-01 01:50:00 ⋯
Keeler.Ave...Roosevelt.Rd 0                   0                   ⋯
East.End.Ave...87th.St    0                   0                   ⋯
NA.                       0                   0                   ⋯
Greenwood.Ave...91st.St   0                   0                   ⋯
Big.Marsh.Park            0                   0                   ⋯
Kildare.Ave...26th.St     0                   0                   ⋯
                          2018-09-13 18:30:00 2018-09-13 18:40:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-13 18:50:00 2018-09-13 19:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-13 19:10:00 2018-09-13 19:20:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-13 19:30:00 2018-09-13 19:40:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-13 19:50:00 2018-09-13 20:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0

In [ ]:
# Checking: they are still in the same order
head(divvy_in.tfull[0])
print('---')
head(divvy_out.tfull[0])
print('---')
head(divvy_inout_cluster$X)

Keeler.Ave...Roosevelt.Rd
East.End.Ave...87th.St
NA.
Greenwood.Ave...91st.St
Big.Marsh.Park
Kildare.Ave...26th.St

[1] "---"

Keeler.Ave...Roosevelt.Rd
East.End.Ave...87th.St
NA.
Greenwood.Ave...91st.St
Big.Marsh.Park
Kildare.Ave...26th.St

[1] "---"

[1] "Keeler.Ave...Roosevelt.Rd" "East.End.Ave...87th.St"
[3] "NA."                       "Greenwood.Ave...91st.St"
[5] "Big.Marsh.Park"            "Kildare.Ave...26th.St"

In [ ]:
# append the cluster labels to the original df
divvy_in.tfullk2 <- data.frame(cbind(divvy_in.tfull, clusterIn = divvy_inout_cluster$clusterIn))
divvy_out.tfullk2 <- data.frame(cbind(divvy_out.tfull, clusterOut = divvy_inout_cluster$clusterOut))

In [ ]:
# checking
head(divvy_in.tfullk2$clusterIn)
head(divvy_out.tfullk2$clusterOut)

[1] 1 1 2 1 1 1

[1] 1 1 2 1 1 1

In [ ]:
# AGGREGATE
# divvy_in.tfullk2_agg <- aggregate(.~clusterIn, data=divvy_in.tfullk2, FUN=sum)

In [ ]:
# AGGREGATE
# divvy_out.tfullk2_agg <- aggregate(.~clusterOut, data=divvy_out.tfullk2, FUN=sum)

In [ ]:
dim(divvy_in)
dim(divvy_out)
dim(divvy_in.tfull)
dim(divvy_out.tfull)
dim(divvy_in.tfullk2)
dim(divvy_out.tfullk2)
dim(divvy_inout_cluster)

[1] 89708   846

[1] 89399   846

[1]   845 89708

[1]   845 89399

[1]   845 89709

[1]   845 89400

[1] 845   4

In [ ]:
tail(divvy_in,1)
tail(divvy_out,1)
tail(divvy_in.tfull,1)
tail(divvy_out.tfull,1)
tail(divvy_in.tfullk2,1)
tail(divvy_out.tfullk2,1)
tail(divvy_inout_cluster,1)

      time_stamp          Keeler.Ave...Roosevelt.Rd East.End.Ave...87th.St NA.
89708 2018-09-15 23:30:00 0                         0                      0
      Greenwood.Ave...91st.St Big.Marsh.Park Kildare.Ave...26th.St
89708 0                       0              0
      Lockwood.Ave...Wrightwood.Ave N.Clark.St...W.Elm.St
89708 0                             0
      Major.Taylor.Trail...124th.St ⋯ Clinton.St...Tilden.St
89708 0                             ⋯ 0
      California.Ave...21st.St Racine.Ave...Wrightwood.Ave Canal.St...Adams.St
89708 0                        0                           0
      Halsted.St...35th.St.... Manor.Ave...Leland.Ave Broadway...Belmont.Ave
89708 0                        0                      0
      Cannon.Dr...Fullerton.Ave Logan.Blvd...Elston.Ave Kosciuszko.Park
89708 1                         0                       0

      time_stamp          Keeler.Ave...Roosevelt.Rd East.End.Ave...87th.St NA.
89399 2018-09-13 20:00:00 0                         0                      0
      Greenwood.Ave...91st.St Big.Marsh.Park Kildare.Ave...26th.St
89399 0                       0              0
      Lockwood.Ave...Wrightwood.Ave N.Clark.St...W.Elm.St
89399 0                             0
      Major.Taylor.Trail...124th.St ⋯ Clinton.St...Tilden.St
89399 0                             ⋯ 1
      California.Ave...21st.St Racine.Ave...Wrightwood.Ave Canal.St...Adams.St
89399 0                        0                           4
      Halsted.St...35th.St.... Manor.Ave...Leland.Ave Broadway...Belmont.Ave
89399 0                        0                      3
      Cannon.Dr...Fullerton.Ave Logan.Blvd...Elston.Ave Kosciuszko.Park
89399 0                         0                       1

                2017-01-01 00:20:00 2017-01-01 00:30:00 2017-01-01 00:40:00
Kosciuszko.Park 0                   0                   0
                2017-01-01 00:50:00 2017-01-01 01:00:00 2017-01-01 01:10:00
Kosciuszko.Park 0                   0                   0
                2017-01-01 01:20:00 2017-01-01 01:30:00 2017-01-01 01:40:00
Kosciuszko.Park 0                   0                   0
                2017-01-01 01:50:00 ⋯ 2018-09-15 22:00:00 2018-09-15 22:10:00
Kosciuszko.Park 0                   ⋯ 0                   0
                2018-09-15 22:20:00 2018-09-15 22:30:00 2018-09-15 22:40:00
Kosciuszko.Park 0                   0                   0
                2018-09-15 22:50:00 2018-09-15 23:00:00 2018-09-15 23:10:00
Kosciuszko.Park 0                   0                   0
                2018-09-15 23:20:00 2018-09-15 23:30:00
Kosciuszko.Park 0                   0

                2017-01-01 00:20:00 2017-01-01 00:30:00 2017-01-01 00:40:00
Kosciuszko.Park 0                   0                   0
                2017-01-01 00:50:00 2017-01-01 01:00:00 2017-01-01 01:10:00
Kosciuszko.Park 0                   0                   0
                2017-01-01 01:20:00 2017-01-01 01:30:00 2017-01-01 01:40:00
Kosciuszko.Park 0                   0                   0
                2017-01-01 01:50:00 ⋯ 2018-09-13 18:30:00 2018-09-13 18:40:00
Kosciuszko.Park 0                   ⋯ 0                   0
                2018-09-13 18:50:00 2018-09-13 19:00:00 2018-09-13 19:10:00
Kosciuszko.Park 0                   0                   0
                2018-09-13 19:20:00 2018-09-13 19:30:00 2018-09-13 19:40:00
Kosciuszko.Park 0                   0                   0
                2018-09-13 19:50:00 2018-09-13 20:00:00
Kosciuszko.Park 1                   1

                X2017.01.01.00.20.00 X2017.01.01.00.30.00 X2017.01.01.00.40.00
Kosciuszko.Park 0                    0                    0
                X2017.01.01.00.50.00 X2017.01.01.01.00.00 X2017.01.01.01.10.00
Kosciuszko.Park 0                    0                    0
                X2017.01.01.01.20.00 X2017.01.01.01.30.00 X2017.01.01.01.40.00
Kosciuszko.Park 0                    0                    0
                X2017.01.01.01.50.00 ⋯ X2018.09.15.22.10.00
Kosciuszko.Park 0                    ⋯ 0
                X2018.09.15.22.20.00 X2018.09.15.22.30.00 X2018.09.15.22.40.00
Kosciuszko.Park 0                    0                    0
                X2018.09.15.22.50.00 X2018.09.15.23.00.00 X2018.09.15.23.10.00
Kosciuszko.Park 0                    0                    0
                X2018.09.15.23.20.00 X2018.09.15.23.30.00 clusterIn
Kosciuszko.Park 0                    0                    1

                X2017.01.01.00.20.00 X2017.01.01.00.30.00 X2017.01.01.00.40.00
Kosciuszko.Park 0                    0                    0
                X2017.01.01.00.50.00 X2017.01.01.01.00.00 X2017.01.01.01.10.00
Kosciuszko.Park 0                    0                    0
                X2017.01.01.01.20.00 X2017.01.01.01.30.00 X2017.01.01.01.40.00
Kosciuszko.Park 0                    0                    0
                X2017.01.01.01.50.00 ⋯ X2018.09.13.18.40.00
Kosciuszko.Park 0                    ⋯ 0
                X2018.09.13.18.50.00 X2018.09.13.19.00.00 X2018.09.13.19.10.00
Kosciuszko.Park 0                    0                    0
                X2018.09.13.19.20.00 X2018.09.13.19.30.00 X2018.09.13.19.40.00
Kosciuszko.Park 0                    0                    0
                X2018.09.13.19.50.00 X2018.09.13.20.00.00 clusterOut
Kosciuszko.Park 1                    1                    1

    X               clusterIn clusterOut clusterDiff
845 Kosciuszko.Park 1         1          0

In [ ]:
divvy_in.tfullk2[1]

                                   X2017.01.01.00.20.00
Keeler.Ave...Roosevelt.Rd          0
East.End.Ave...87th.St             0
NA.                                0
Greenwood.Ave...91st.St            0
Big.Marsh.Park                     0
Kildare.Ave...26th.St              0
Lockwood.Ave...Wrightwood.Ave      0
N.Clark.St...W.Elm.St              0
Major.Taylor.Trail...124th.St      0
Vincennes.Ave...104th.St           0
Base...2132.W.Hubbard.Warehouse    0
Lavergne...Fullerton               0
Dauphin.Ave...103rd.St             0
Clyde.Ave...87th.St                0
Stony.Island.Ave...90th.St         0
Elston.Ave...Cortland.St           0
Cicero.Ave...Grace.St              0
Maryland.Ave...104th.St            0
Pulaski.Rd...21st.St               0
Marquette.Ave...89th.St            0
Avenue.L...114th.St                0
Roscoe...Harlem                    0
Wentworth.Ave...Cermak.Rd          0
State.St...95th.St                 0
State.St...123rd.St                0
Avenue.O...134th.St                0
W.Armitage.Ave...N.Sheffield.Ave   0
W.103rd.St...S.Avers.Ave           0
S.Michigan.Ave...E.118th.St        0
Eggleston.Ave...69th.St            0
⋮                                  ⋮
Franklin.St...Quincy.St            0
Halsted.St...Diversey.Pkwy         0
Campbell.Ave...North.Ave           0
Noble.St...Milwaukee.Ave           0
Albany..Kedzie..Ave...Montrose.Ave 0
California.Ave...23rd.Pl           0
Wolcott.Ave...Polk.St              0
Kedzie.Ave...Chicago.Ave           0
Racine.Ave...15th.St               0
Federal.St...Polk.St               0
Claremont.Ave...Hirsch.St          0
Wabash.Ave...83rd.St               0
Ogden.Ave...Chicago.Ave            1
Lakefront.Trail...Wilson.Ave       0
Washtenaw.Ave...15th.St....        0
LaSalle.St...Washington.St         0
Rush.St...Cedar.St                 0
Michigan.Ave...Madison.St          0
Chicago.Ave...Washington.St        0
Clark.St...North.Ave               0
Clinton.St...Tilden.St             1
California.Ave...21st.St           0
Racine.Ave...Wrightwood.Ave        0
Canal.St...Adams.St                0
Halsted.St...35th.St....           0
Manor.Ave...Leland.Ave             0
Broadway...Belmont.Ave             0
Cannon.Dr...Fullerton.Ave          0
Logan.Blvd...Elston.Ave            0
Kosciuszko.Park                    0

In [ ]:
divvy_in.tfullk2_1 <- divvy_in.tfullk2[divvy_in.tfullk2$clusterIn==1,][1:89708]
divvy_in.tfullk2_1 <- data.frame(sum=colSums(divvy_in.tfullk2_1[,-1]))
head(divvy_in.tfullk2_1)

                     sum
X2017.01.01.00.30.00 5
X2017.01.01.00.40.00 7
X2017.01.01.00.50.00 4
X2017.01.01.01.00.00 1
X2017.01.01.01.10.00 4
X2017.01.01.01.20.00 3

In [ ]:
divvy_in.tfullk2_2 <- divvy_in.tfullk2[divvy_in.tfullk2$clusterIn==2,][1:89708]
divvy_in.tfullk2_2 <- data.frame(sum=colSums(divvy_in.tfullk2_2[,-1]))
head(divvy_in.tfullk2_2)

                     sum
X2017.01.01.00.30.00 1
X2017.01.01.00.40.00 6
X2017.01.01.00.50.00 3
X2017.01.01.01.00.00 4
X2017.01.01.01.10.00 3
X2017.01.01.01.20.00 5

In [ ]:
divvy_out.tfullk2_1 <- divvy_out.tfullk2[divvy_out.tfullk2$clusterOut==1,][1:89399]
divvy_out.tfullk2_1 <- data.frame(sum=colSums(divvy_out.tfullk2_1[,-1]))
head(divvy_out.tfullk2_1)

                     sum
X2017.01.01.00.30.00 6
X2017.01.01.00.40.00 4
X2017.01.01.00.50.00 1
X2017.01.01.01.00.00 4
X2017.01.01.01.10.00 3
X2017.01.01.01.20.00 5

In [ ]:
divvy_out.tfullk2_2 <- divvy_out.tfullk2[divvy_out.tfullk2$clusterOut==2,][1:89399]
divvy_out.tfullk2_2 <- data.frame(sum=colSums(divvy_out.tfullk2_2[,-1]))
head(divvy_out.tfullk2_2)

                     sum
X2017.01.01.00.30.00 9
X2017.01.01.00.40.00 4
X2017.01.01.00.50.00 1
X2017.01.01.01.00.00 0
X2017.01.01.01.10.00 5
X2017.01.01.01.20.00 2

In [ ]:
k1_in_ADI <- sum(divvy_in.tfullk2_1$sum>=0,na.rm = TRUE)/sum(divvy_in.tfullk2_1$sum>0,na.rm = TRUE) 
k2_in_ADI <- sum(divvy_in.tfullk2_2$sum>=0,na.rm = TRUE)/sum(divvy_in.tfullk2_2$sum>0,na.rm = TRUE)
k1_out_ADI <- sum(divvy_out.tfullk2_1$sum>=0,na.rm = TRUE)/sum(divvy_out.tfullk2_1$sum>0,na.rm = TRUE) 
k2_out_ADI <- sum(divvy_out.tfullk2_2$sum>=0,na.rm = TRUE)/sum(divvy_out.tfullk2_2$sum>0,na.rm = TRUE)

k1_in_ADI
k2_in_ADI
k1_out_ADI
k2_out_ADI

[1] 1.07141

[1] 1.098045

[1] 1.067299

[1] 1.105959

In [ ]:
k1_in_CV2 <- (sd(divvy_in.tfullk2_1$sum)/mean(divvy_in.tfullk2_1$sum))^2
k2_in_CV2 <- (sd(divvy_in.tfullk2_2$sum)/mean(divvy_in.tfullk2_2$sum))^2
k1_out_CV2 <- (sd(divvy_out.tfullk2_1$sum)/mean(divvy_out.tfullk2_1$sum))^2
k2_out_CV2 <- (sd(divvy_out.tfullk2_2$sum)/mean(divvy_out.tfullk2_2$sum))^2

k1_in_CV2 
k2_in_CV2 
k1_out_CV2 
k2_out_CV2

[1] 1.260678

[1] 1.495088

[1] 1.188333

[1] 1.587999

In [ ]:
colnames(community)

 [1] "X"                "station_id"       "lng"              "lat"
 [5] "cord"             "station_name"     "Nbh_id"           "com_id"
 [9] "Docks.in.Service" "station_name1"

In [ ]:
divvy_in.tfull_ <- divvy_in.tfull
divvy_in.tfull1 <- cbind(station_name1=rownames(divvy_in.tfull_),divvy_in.tfull_)
rownames(divvy_in.tfull1) <- 1:nrow(divvy_in.tfull1)
head(divvy_in.tfull1)

  station_name1             2017-01-01 00:20:00 2017-01-01 00:30:00
1 Keeler.Ave...Roosevelt.Rd 0                   0
2 East.End.Ave...87th.St    0                   0
3 NA.                       0                   0
4 Greenwood.Ave...91st.St   0                   0
5 Big.Marsh.Park            0                   0
6 Kildare.Ave...26th.St     0                   0
  2017-01-01 00:40:00 2017-01-01 00:50:00 2017-01-01 01:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2017-01-01 01:10:00 2017-01-01 01:20:00 2017-01-01 01:30:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2017-01-01 01:40:00 ⋯ 2018-09-15 22:00:00 2018-09-15 22:10:00
1 0                   ⋯ 0                   0
2 0                   ⋯ 0                   0
3 0                   ⋯ 0                   0
4 0                   ⋯ 0                   0
5 0                   ⋯ 0                   0
6 0                   ⋯ 0                   0
  2018-09-15 22:20:00 2018-09-15 22:30:00 2018-09-15 22:40:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2018-09-15 22:50:00 2018-09-15 23:00:00 2018-09-15 23:10:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2018-09-15 23:20:00 2018-09-15 23:30:00
1 0                   0
2 0                   0
3 0                   0
4 0                   0
5 0                   0
6 0                   0

In [ ]:
divvy_out.tfull_ <- divvy_out.tfull
divvy_out.tfull1 <- cbind(station_name1=rownames(divvy_out.tfull_),divvy_out.tfull_)
rownames(divvy_out.tfull1) <- 1:nrow(divvy_out.tfull1)
head(divvy_out.tfull1)

  station_name1             2017-01-01 00:20:00 2017-01-01 00:30:00
1 Keeler.Ave...Roosevelt.Rd 0                   0
2 East.End.Ave...87th.St    0                   0
3 NA.                       0                   0
4 Greenwood.Ave...91st.St   0                   0
5 Big.Marsh.Park            0                   0
6 Kildare.Ave...26th.St     0                   0
  2017-01-01 00:40:00 2017-01-01 00:50:00 2017-01-01 01:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2017-01-01 01:10:00 2017-01-01 01:20:00 2017-01-01 01:30:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2017-01-01 01:40:00 ⋯ 2018-09-13 18:30:00 2018-09-13 18:40:00
1 0                   ⋯ 0                   0
2 0                   ⋯ 0                   0
3 0                   ⋯ 0                   0
4 0                   ⋯ 0                   0
5 0                   ⋯ 0                   0
6 0                   ⋯ 0                   0
  2018-09-13 18:50:00 2018-09-13 19:00:00 2018-09-13 19:10:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2018-09-13 19:20:00 2018-09-13 19:30:00 2018-09-13 19:40:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2018-09-13 19:50:00 2018-09-13 20:00:00
1 0                   0
2 0                   0
3 0                   0
4 0                   0
5 0                   0
6 0                   0

In [ ]:
community[community$station_name1=='Buckingham.Fountain',]
dim(community)

    X   station_id lng       lat      cord
1     0 2          -87.62053 41.87650 (-87.62052684219132, 41.87650284189418)
879 878 15541      -87.62091 41.87571 (-87.62090982256507, 41.87570813111998)
    station_name        Nbh_id com_id Docks.in.Service station_name1
1   Buckingham Fountain 32     32     39               Buckingham.Fountain
879 Buckingham Fountain 32     32     15               Buckingham.Fountain

[1] 1361   10

In [ ]:
community_new <- community[-c(879),]
dim(community_new)

[1] 1360   10

In [ ]:
divvy_in.tfull2 <- merge(divvy_in.tfull1,community_new[,c('Nbh_id','com_id','station_name1')],by = 'station_name1')
divvy_out.tfull2 <- merge(divvy_out.tfull1,community_new[,c('Nbh_id','com_id','station_name1')],by = 'station_name1')
head(divvy_in.tfull2,1)
head(divvy_out.tfull2,1)

  station_name1              2017-01-01 00:20:00 2017-01-01 00:30:00
1 Aberdeen.St...Jackson.Blvd 0                   0
  2017-01-01 00:40:00 2017-01-01 00:50:00 2017-01-01 01:00:00
1 0                   0                   0
  2017-01-01 01:10:00 2017-01-01 01:20:00 2017-01-01 01:30:00
1 0                   0                   0
  2017-01-01 01:40:00 ⋯ 2018-09-15 22:20:00 2018-09-15 22:30:00
1 0                   ⋯ 0                   0
  2018-09-15 22:40:00 2018-09-15 22:50:00 2018-09-15 23:00:00
1 0                   0                   0
  2018-09-15 23:10:00 2018-09-15 23:20:00 2018-09-15 23:30:00 Nbh_id com_id
1 0                   0                   0                   28.2   28

  station_name1              2017-01-01 00:20:00 2017-01-01 00:30:00
1 Aberdeen.St...Jackson.Blvd 0                   0
  2017-01-01 00:40:00 2017-01-01 00:50:00 2017-01-01 01:00:00
1 0                   0                   0
  2017-01-01 01:10:00 2017-01-01 01:20:00 2017-01-01 01:30:00
1 0                   0                   0
  2017-01-01 01:40:00 ⋯ 2018-09-13 18:50:00 2018-09-13 19:00:00
1 0                   ⋯ 0                   0
  2018-09-13 19:10:00 2018-09-13 19:20:00 2018-09-13 19:30:00
1 0                   0                   2
  2018-09-13 19:40:00 2018-09-13 19:50:00 2018-09-13 20:00:00 Nbh_id com_id
1 2                   0                   0                   28.2   28

In [ ]:
head(divvy_in.tfull2[,1:5])

  station_name1              2017-01-01 00:20:00 2017-01-01 00:30:00
1 Aberdeen.St...Jackson.Blvd 0                   0
2 Aberdeen.St...Jackson.Blvd 0                   0
3 Aberdeen.St...Monroe.St    0                   0
4 Aberdeen.St...Monroe.St    0                   0
5 Aberdeen.St...Randolph.St  0                   0
6 Aberdeen.St...Randolph.St  0                   0
  2017-01-01 00:40:00 2017-01-01 00:50:00
1 0                   0
2 0                   0
3 0                   0
4 0                   0
5 0                   0
6 0                   0

In [ ]:
head(divvy_in)

  time_stamp          Keeler.Ave...Roosevelt.Rd East.End.Ave...87th.St NA.
1 2017-01-01 00:20:00 0                         0                      0
2 2017-01-01 00:30:00 0                         0                      0
3 2017-01-01 00:40:00 0                         0                      0
4 2017-01-01 00:50:00 0                         0                      0
5 2017-01-01 01:00:00 0                         0                      0
6 2017-01-01 01:10:00 0                         0                      0
  Greenwood.Ave...91st.St Big.Marsh.Park Kildare.Ave...26th.St
1 0                       0              0
2 0                       0              0
3 0                       0              0
4 0                       0              0
5 0                       0              0
6 0                       0              0
  Lockwood.Ave...Wrightwood.Ave N.Clark.St...W.Elm.St
1 0                             0
2 0                             0
3 0                             0
4 0                             0
5 0                             0
6 0                             0
  Major.Taylor.Trail...124th.St ⋯ Clinton.St...Tilden.St
1 0                             ⋯ 1
2 0                             ⋯ 0
3 0                             ⋯ 0
4 0                             ⋯ 0
5 0                             ⋯ 0
6 0                             ⋯ 0
  California.Ave...21st.St Racine.Ave...Wrightwood.Ave Canal.St...Adams.St
1 0                        0                           0
2 0                        0                           0
3 0                        0                           0
4 0                        0                           0
5 0                        0                           0
6 0                        0                           0
  Halsted.St...35th.St.... Manor.Ave...Leland.Ave Broadway...Belmont.Ave
1 0                        0                      0
2 0                        0                      0
3 0                        0                      0
4 0                        0                      0
5 0                        0                      0
6 0                        0                      0
  Cannon.Dr...Fullerton.Ave Logan.Blvd...Elston.Ave Kosciuszko.Park
1 0                         0                       0
2 0                         0                       0
3 0                         0                       0
4 0                         0                       0
5 0                         0                       0
6 0                         0                       0

Neighborhood Hourly

In [ ]:
divvy_in$time_stamp <- strptime(divvy_in$time_stamp, '%Y-%m-%d %H:%M:%S', tz="America/Chicago")
divvy_in.h <- aggregate(divvy_in[,2:846], 
                 list(hour=cut(as.POSIXct(divvy_in$time_stamp), "hour")), sum)
head(divvy_in.h)

  hour                Keeler.Ave...Roosevelt.Rd East.End.Ave...87th.St NA.
1 2017-01-01 00:00:00 0                         0                      0
2 2017-01-01 01:00:00 0                         0                      0
3 2017-01-01 02:00:00 0                         0                      0
4 2017-01-01 03:00:00 0                         0                      0
5 2017-01-01 04:00:00 0                         0                      0
6 2017-01-01 05:00:00 0                         0                      0
  Greenwood.Ave...91st.St Big.Marsh.Park Kildare.Ave...26th.St
1 0                       0              0
2 0                       0              0
3 0                       0              0
4 0                       0              0
5 0                       0              0
6 0                       0              0
  Lockwood.Ave...Wrightwood.Ave N.Clark.St...W.Elm.St
1 0                             0
2 0                             0
3 0                             0
4 0                             0
5 0                             0
6 0                             0
  Major.Taylor.Trail...124th.St ⋯ Clinton.St...Tilden.St
1 0                             ⋯ 1
2 0                             ⋯ 0
3 0                             ⋯ 0
4 0                             ⋯ 0
5 0                             ⋯ 0
6 0                             ⋯ 0
  California.Ave...21st.St Racine.Ave...Wrightwood.Ave Canal.St...Adams.St
1 0                        0                           0
2 0                        1                           0
3 0                        0                           0
4 0                        0                           0
5 0                        0                           0
6 0                        0                           0
  Halsted.St...35th.St.... Manor.Ave...Leland.Ave Broadway...Belmont.Ave
1 0                        0                      0
2 0                        0                      1
3 0                        0                      1
4 0                        0                      0
5 0                        0                      0
6 0                        0                      0
  Cannon.Dr...Fullerton.Ave Logan.Blvd...Elston.Ave Kosciuszko.Park
1 0                         0                       0
2 0                         0                       0
3 0                         0                       0
4 0                         0                       0
5 0                         0                       0
6 0                         0                       0

In [ ]:
divvy_out$time_stamp <- strptime(divvy_out$time_stamp, '%Y-%m-%d %H:%M:%S', tz="America/Chicago")
divvy_out.h <- aggregate(divvy_in[,2:846], 
                 list(hour=cut(as.POSIXct(divvy_in$time_stamp), "hour")), sum)
head(divvy_out.h)

  hour                Keeler.Ave...Roosevelt.Rd East.End.Ave...87th.St NA.
1 2017-01-01 00:00:00 0                         0                      0
2 2017-01-01 01:00:00 0                         0                      0
3 2017-01-01 02:00:00 0                         0                      0
4 2017-01-01 03:00:00 0                         0                      0
5 2017-01-01 04:00:00 0                         0                      0
6 2017-01-01 05:00:00 0                         0                      0
  Greenwood.Ave...91st.St Big.Marsh.Park Kildare.Ave...26th.St
1 0                       0              0
2 0                       0              0
3 0                       0              0
4 0                       0              0
5 0                       0              0
6 0                       0              0
  Lockwood.Ave...Wrightwood.Ave N.Clark.St...W.Elm.St
1 0                             0
2 0                             0
3 0                             0
4 0                             0
5 0                             0
6 0                             0
  Major.Taylor.Trail...124th.St ⋯ Clinton.St...Tilden.St
1 0                             ⋯ 1
2 0                             ⋯ 0
3 0                             ⋯ 0
4 0                             ⋯ 0
5 0                             ⋯ 0
6 0                             ⋯ 0
  California.Ave...21st.St Racine.Ave...Wrightwood.Ave Canal.St...Adams.St
1 0                        0                           0
2 0                        1                           0
3 0                        0                           0
4 0                        0                           0
5 0                        0                           0
6 0                        0                           0
  Halsted.St...35th.St.... Manor.Ave...Leland.Ave Broadway...Belmont.Ave
1 0                        0                      0
2 0                        0                      1
3 0                        0                      1
4 0                        0                      0
5 0                        0                      0
6 0                        0                      0
  Cannon.Dr...Fullerton.Ave Logan.Blvd...Elston.Ave Kosciuszko.Park
1 0                         0                       0
2 0                         0                       0
3 0                         0                       0
4 0                         0                       0
5 0                         0                       0
6 0                         0                       0

In [ ]:
# TRANSPOSE

# first remember the names
hour_divin <- divvy_in.h$hour
hour_divout <- divvy_out.h$hour

# transpose all but the first column (name)
divvy_in.tfullh <- as.data.frame(t(divvy_in.h[,-1]))
colnames(divvy_in.tfullh) <- hour_divin
head(divvy_in.tfullh)

divvy_out.tfullh <- as.data.frame(t(divvy_out.h[,-1]))
colnames(divvy_out.tfullh) <- hour_divout
head(divvy_out.tfullh)

                          2017-01-01 00:00:00 2017-01-01 01:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 02:00:00 2017-01-01 03:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 04:00:00 2017-01-01 05:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 06:00:00 2017-01-01 07:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 08:00:00 2017-01-01 09:00:00 ⋯
Keeler.Ave...Roosevelt.Rd 0                   0                   ⋯
East.End.Ave...87th.St    0                   0                   ⋯
NA.                       0                   0                   ⋯
Greenwood.Ave...91st.St   0                   0                   ⋯
Big.Marsh.Park            0                   0                   ⋯
Kildare.Ave...26th.St     0                   0                   ⋯
                          2018-09-15 14:00:00 2018-09-15 15:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 16:00:00 2018-09-15 17:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 18:00:00 2018-09-15 19:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 20:00:00 2018-09-15 21:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 22:00:00 2018-09-15 23:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0

                          2017-01-01 00:00:00 2017-01-01 01:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 02:00:00 2017-01-01 03:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 04:00:00 2017-01-01 05:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 06:00:00 2017-01-01 07:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2017-01-01 08:00:00 2017-01-01 09:00:00 ⋯
Keeler.Ave...Roosevelt.Rd 0                   0                   ⋯
East.End.Ave...87th.St    0                   0                   ⋯
NA.                       0                   0                   ⋯
Greenwood.Ave...91st.St   0                   0                   ⋯
Big.Marsh.Park            0                   0                   ⋯
Kildare.Ave...26th.St     0                   0                   ⋯
                          2018-09-15 14:00:00 2018-09-15 15:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 16:00:00 2018-09-15 17:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 18:00:00 2018-09-15 19:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 20:00:00 2018-09-15 21:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0
                          2018-09-15 22:00:00 2018-09-15 23:00:00
Keeler.Ave...Roosevelt.Rd 0                   0
East.End.Ave...87th.St    0                   0
NA.                       0                   0
Greenwood.Ave...91st.St   0                   0
Big.Marsh.Park            0                   0
Kildare.Ave...26th.St     0                   0

In [ ]:
divvy_in.tfullh_ <- divvy_in.tfullh
divvy_in.tfullh1 <- cbind(station_name1=rownames(divvy_in.tfullh_),divvy_in.tfullh_)
rownames(divvy_in.tfullh1) <- 1:nrow(divvy_in.tfullh1)
head(divvy_in.tfullh1)

  station_name1             2017-01-01 00:00:00 2017-01-01 01:00:00
1 Keeler.Ave...Roosevelt.Rd 0                   0
2 East.End.Ave...87th.St    0                   0
3 NA.                       0                   0
4 Greenwood.Ave...91st.St   0                   0
5 Big.Marsh.Park            0                   0
6 Kildare.Ave...26th.St     0                   0
  2017-01-01 02:00:00 2017-01-01 03:00:00 2017-01-01 04:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2017-01-01 05:00:00 2017-01-01 06:00:00 2017-01-01 07:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2017-01-01 08:00:00 ⋯ 2018-09-15 14:00:00 2018-09-15 15:00:00
1 0                   ⋯ 0                   0
2 0                   ⋯ 0                   0
3 0                   ⋯ 0                   0
4 0                   ⋯ 0                   0
5 0                   ⋯ 0                   0
6 0                   ⋯ 0                   0
  2018-09-15 16:00:00 2018-09-15 17:00:00 2018-09-15 18:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2018-09-15 19:00:00 2018-09-15 20:00:00 2018-09-15 21:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2018-09-15 22:00:00 2018-09-15 23:00:00
1 0                   0
2 0                   0
3 0                   0
4 0                   0
5 0                   0
6 0                   0

In [ ]:
divvy_out.tfullh_ <- divvy_out.tfullh
divvy_out.tfullh1 <- cbind(station_name1=rownames(divvy_out.tfullh_),divvy_out.tfullh_)
rownames(divvy_out.tfullh1) <- 1:nrow(divvy_out.tfullh1)
head(divvy_out.tfullh1)

  station_name1             2017-01-01 00:00:00 2017-01-01 01:00:00
1 Keeler.Ave...Roosevelt.Rd 0                   0
2 East.End.Ave...87th.St    0                   0
3 NA.                       0                   0
4 Greenwood.Ave...91st.St   0                   0
5 Big.Marsh.Park            0                   0
6 Kildare.Ave...26th.St     0                   0
  2017-01-01 02:00:00 2017-01-01 03:00:00 2017-01-01 04:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2017-01-01 05:00:00 2017-01-01 06:00:00 2017-01-01 07:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2017-01-01 08:00:00 ⋯ 2018-09-15 14:00:00 2018-09-15 15:00:00
1 0                   ⋯ 0                   0
2 0                   ⋯ 0                   0
3 0                   ⋯ 0                   0
4 0                   ⋯ 0                   0
5 0                   ⋯ 0                   0
6 0                   ⋯ 0                   0
  2018-09-15 16:00:00 2018-09-15 17:00:00 2018-09-15 18:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2018-09-15 19:00:00 2018-09-15 20:00:00 2018-09-15 21:00:00
1 0                   0                   0
2 0                   0                   0
3 0                   0                   0
4 0                   0                   0
5 0                   0                   0
6 0                   0                   0
  2018-09-15 22:00:00 2018-09-15 23:00:00
1 0                   0
2 0                   0
3 0                   0
4 0                   0
5 0                   0
6 0                   0

In [ ]:
divvy_in.tfullh2 <- merge(divvy_in.tfullh1,community_new[,c('Nbh_id','com_id','station_name1')],by = 'station_name1')
divvy_out.tfullh2 <- merge(divvy_out.tfullh1,community_new[,c('Nbh_id','com_id','station_name1')],by = 'station_name1')
head(divvy_in.tfullh2,1)
head(divvy_out.tfullh2,1)

  station_name1              2017-01-01 00:00:00 2017-01-01 01:00:00
1 Aberdeen.St...Jackson.Blvd 0                   0
  2017-01-01 02:00:00 2017-01-01 03:00:00 2017-01-01 04:00:00
1 0                   0                   0
  2017-01-01 05:00:00 2017-01-01 06:00:00 2017-01-01 07:00:00
1 0                   0                   0
  2017-01-01 08:00:00 ⋯ 2018-09-15 16:00:00 2018-09-15 17:00:00
1 0                   ⋯ 3                   2
  2018-09-15 18:00:00 2018-09-15 19:00:00 2018-09-15 20:00:00
1 3                   6                   6
  2018-09-15 21:00:00 2018-09-15 22:00:00 2018-09-15 23:00:00 Nbh_id com_id
1 0                   3                   0                   28.2   28

  station_name1              2017-01-01 00:00:00 2017-01-01 01:00:00
1 Aberdeen.St...Jackson.Blvd 0                   0
  2017-01-01 02:00:00 2017-01-01 03:00:00 2017-01-01 04:00:00
1 0                   0                   0
  2017-01-01 05:00:00 2017-01-01 06:00:00 2017-01-01 07:00:00
1 0                   0                   0
  2017-01-01 08:00:00 ⋯ 2018-09-15 16:00:00 2018-09-15 17:00:00
1 0                   ⋯ 3                   2
  2018-09-15 18:00:00 2018-09-15 19:00:00 2018-09-15 20:00:00
1 3                   6                   6
  2018-09-15 21:00:00 2018-09-15 22:00:00 2018-09-15 23:00:00 Nbh_id com_id
1 0                   3                   0                   28.2   28

In [ ]:
# AGGREGATE
divvy_in.tfullh2n <- aggregate(.~Nbh_id, data=divvy_in.tfullh2[,2:14952], FUN=sum)
head(divvy_in.tfullh2n,1)

  Nbh_id 2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
1 1      3                   0                   0
  2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
1 2                   1                   0
  2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00 ⋯
1 2                   0                   0                   ⋯
  2018-09-15 14:00:00 2018-09-15 15:00:00 2018-09-15 16:00:00
1 21                  22                  32
  2018-09-15 17:00:00 2018-09-15 18:00:00 2018-09-15 19:00:00
1 29                  26                  11
  2018-09-15 20:00:00 2018-09-15 21:00:00 2018-09-15 22:00:00
1 15                  8                   15
  2018-09-15 23:00:00
1 6

In [ ]:
# AGGREGATE
divvy_out.tfullh2n <- aggregate(.~Nbh_id, data=divvy_out.tfullh2[,2:14952], FUN=sum)
head(divvy_out.tfullh2n,1)

  Nbh_id 2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
1 1      3                   0                   0
  2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
1 2                   1                   0
  2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00 ⋯
1 2                   0                   0                   ⋯
  2018-09-15 14:00:00 2018-09-15 15:00:00 2018-09-15 16:00:00
1 21                  22                  32
  2018-09-15 17:00:00 2018-09-15 18:00:00 2018-09-15 19:00:00
1 29                  26                  11
  2018-09-15 20:00:00 2018-09-15 21:00:00 2018-09-15 22:00:00
1 15                  8                   15
  2018-09-15 23:00:00
1 6

In [ ]:
rowSums(divvy_in.tfullh2n[1,])
head(divvy_in.tfullh2n,1)

     1
106434

  Nbh_id 2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
1 1      3                   0                   0
  2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
1 2                   1                   0
  2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00 ⋯
1 2                   0                   0                   ⋯
  2018-09-15 14:00:00 2018-09-15 15:00:00 2018-09-15 16:00:00
1 21                  22                  32
  2018-09-15 17:00:00 2018-09-15 18:00:00 2018-09-15 19:00:00
1 29                  26                  11
  2018-09-15 20:00:00 2018-09-15 21:00:00 2018-09-15 22:00:00
1 15                  8                   15
  2018-09-15 23:00:00
1 6

In [ ]:
# ADI
sum(divvy_in.tfullh2n[1,2:14951]>=0,na.rm=TRUE)/sum(divvy_in.tfullh2n[1,2:14951]>0,na.rm=TRUE)

# CV2
(sd(divvy_in.tfullh2n[1,2:14951])/(sum(divvy_in.tfullh2n[1,2:14951])/14950))^2

[1] 1.321956

[1] 1.504304

In [ ]:
ADI_nbh <- list()
CV2_nbh <- list()
for (i in 1:169) {
  ADI <- sum(divvy_in.tfullh2n[i,2:14951]>=0,na.rm=TRUE)/sum(divvy_in.tfullh2n[i,2:14951]>0,na.rm=TRUE)
  CV2 <- (sd(divvy_in.tfullh2n[i,2:14951])/(sum(divvy_in.tfullh2n[i,2:14951])/14950))^2
  ADI_nbh <- append(ADI_nbh,ADI)
  CV2_nbh <- append(CV2_nbh,CV2)
}

In [ ]:
length(ADI_nbh)
head(ADI_nbh)
length(CV2_nbh)
head(CV2_nbh)

[1] 169

[[1]]
[1] 1.321956

[[2]]
[1] 2.370006

[[3]]
[1] 4.619901

[[4]]
[1] 9.540523

[[5]]
[1] 7.573455

[[6]]
[1] 5.393218

[1] 169

[[1]]
[1] 1.504304

[[2]]
[1] 2.88421

[[3]]
[1] 5.29106

[[4]]
[1] 10.32138

[[5]]
[1] 8.203588

[[6]]
[1] 6.124525

In [ ]:
ADI_CV2_Nbh <- do.call(rbind,Map(data.frame,Nbh_row=1:169,ADI=ADI_nbh,CV2=CV2_nbh))

In [ ]:
head(ADI_CV2_Nbh)

  Nbh_row ADI      CV2
1 1       1.321956  1.504304
2 2       2.370006  2.884210
3 3       4.619901  5.291060
4 4       9.540523 10.321384
5 5       7.573455  8.203588
6 6       5.393218  6.124525

In [ ]:
# SMOOTH
ADI_CV2_Nbh[(ADI_CV2_Nbh$ADI<1.32 & ADI_CV2_Nbh$CV2<0.49),]

     Nbh_row ADI CV2

In [ ]:
# INTERMITTENT
ADI_CV2_Nbh[(ADI_CV2_Nbh$ADI>=1.32 & ADI_CV2_Nbh$CV2<0.49),]

      Nbh_row ADI CV2
NA    NA      NA  NA
NA.1  NA      NA  NA
NA.2  NA      NA  NA
NA.3  NA      NA  NA
NA.4  NA      NA  NA
NA.5  NA      NA  NA
NA.6  NA      NA  NA
NA.7  NA      NA  NA
NA.8  NA      NA  NA
NA.9  NA      NA  NA
NA.10 NA      NA  NA
NA.11 NA      NA  NA
NA.12 NA      NA  NA
NA.13 NA      NA  NA
NA.14 NA      NA  NA
NA.15 NA      NA  NA
NA.16 NA      NA  NA
NA.17 NA      NA  NA
NA.18 NA      NA  NA
NA.19 NA      NA  NA
NA.20 NA      NA  NA
NA.21 NA      NA  NA
NA.22 NA      NA  NA
NA.23 NA      NA  NA
NA.24 NA      NA  NA
NA.25 NA      NA  NA
NA.26 NA      NA  NA
NA.27 NA      NA  NA
NA.28 NA      NA  NA
NA.29 NA      NA  NA
NA.30 NA      NA  NA
NA.31 NA      NA  NA
NA.32 NA      NA  NA

In [ ]:
# ERRATIC
ADI_CV2_Nbh[(ADI_CV2_Nbh$ADI<1.32 & ADI_CV2_Nbh$CV2>=0.49),]

    Nbh_row ADI      CV2
23   23     1.192946 1.662020
29   29     1.234619 1.906279
30   30     1.253353 2.657881
34   34     1.235129 1.387616
35   35     1.206910 1.783593
39   39     1.154262 1.284335
40   40     1.220707 1.686323
41   41     1.211900 2.293007
56   56     1.206813 2.764604
69   69     1.234721 1.674481
76   76     1.206521 1.696242
77   77     1.142268 2.184117
79   79     1.275380 1.397314
91   91     1.300000 1.811869
162 162     1.170163 2.010068

In [ ]:
# LUMPY
ADI_CV2_Nbh[(ADI_CV2_Nbh$ADI>=1.32 & ADI_CV2_Nbh$CV2>=0.49),]

      Nbh_row ADI        CV2
1      1      1.321956    1.504304
2      2      2.370006    2.884210
3      3      4.619901    5.291060
4      4      9.540523   10.321384
5      5      7.573455    8.203588
6      6      5.393218    6.124525
7      7      1.668899    2.141851
8      8      1.479612    1.989279
9      9      2.239700    4.416411
10    10      3.765743    5.357822
11    11      3.645452    4.719925
12    12      1.753460    1.894245
13    13      2.517259    3.197382
14    14      3.874061    4.621249
15    15      4.113924    4.557398
16    16      1.523179    1.949840
17    17      2.225696    2.432116
18    18      2.960982    3.512489
19    19      1.417062    1.716759
20    20      2.250151    2.802122
21    21      1.340807    1.736007
22    22      1.489934    1.670605
24    24      1.448784    1.909800
25    25      1.324415    1.965774
26    26      1.873199    2.221011
27    27      1.466837    2.802538
28    28      1.426935    1.945768
31    31      1.464538    1.746030
32    32      1.397980    1.666131
33    33      1.592968    2.281367
⋮     ⋮       ⋮          ⋮
NA.17  NA             NA         NA
NA.18  NA             NA         NA
NA.19  NA             NA         NA
NA.20  NA             NA         NA
NA.21  NA             NA         NA
NA.22  NA             NA         NA
NA.23  NA             NA         NA
146   146       5.658592   6.383981
147   147       2.006981   2.378354
148   148      10.936357  14.033026
149   149      14.170616  14.583085
150   150      35.680191  48.929534
151   151      13.615665  15.908056
152   152     132.300885 148.602907
153   153     106.785714 114.621000
154   154      14.628180  16.520593
NA.24  NA             NA         NA
NA.25  NA             NA         NA
NA.26  NA             NA         NA
NA.27  NA             NA         NA
NA.28  NA             NA         NA
NA.29  NA             NA         NA
NA.30  NA             NA         NA
NA.31  NA             NA         NA
NA.32  NA             NA         NA
165   165       2.229014   2.750419
166   166       1.758824   2.289547
167   167       2.762890   4.574981
168   168       3.617227   4.434217
169   169       1.942315   2.101925

In [ ]:
sum(divvy_in.tfullh2n[1,2:14951]>=0,na.rm=TRUE)

[1] 14950

In [ ]:
erratic_nbh <- ADI_CV2_Nbh[(ADI_CV2_Nbh$ADI<1.32 & ADI_CV2_Nbh$CV2>=0.49),]
erratic_nbh[,1]

 [1]  23  29  30  34  35  39  40  41  56  69  76  77  79  91 162

In [ ]:
for (i in erratic_nbh[,1]){
  countrow <- sum(divvy_in.tfullh2n[i,2:14951]>0,na.rm=TRUE)
  cat(i,' : ',countrow,'\n')
}

23  :  12532
29  :  12109
30  :  11928
34  :  12104
35  :  12387
39  :  12952
40  :  12247
41  :  12336
56  :  12388
69  :  12108
76  :  12391
77  :  13088
79  :  11722
91  :  11500
162  :  12776

In [ ]:
divvy_in.tfullh2n[77,1:14951]

   Nbh_id 2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
77 28.2   2                   4                   2
   2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
77 0                   0                   0
   2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00 ⋯
77 0                   0                   2                   ⋯
   2018-09-15 14:00:00 2018-09-15 15:00:00 2018-09-15 16:00:00
77 102                 92                  94
   2018-09-15 17:00:00 2018-09-15 18:00:00 2018-09-15 19:00:00
77 84                  86                  84
   2018-09-15 20:00:00 2018-09-15 21:00:00 2018-09-15 22:00:00
77 68                  60                  36
   2018-09-15 23:00:00
77 12

In [ ]:
ADI_nbh_out <- list()
CV2_nbh_out <- list()
for (i in 1:169) {
  ADI <- sum(divvy_out.tfullh2n[i,2:14951]>=0,na.rm=TRUE)/sum(divvy_out.tfullh2n[i,2:14951]>0,na.rm=TRUE)
  CV2 <- (sd(divvy_out.tfullh2n[i,2:14951])/(sum(divvy_out.tfullh2n[i,2:14951])/14950))^2
  ADI_nbh_out <- append(ADI_nbh_out,ADI)
  CV2_nbh_out <- append(CV2_nbh_out,CV2)
}

In [ ]:
length(ADI_nbh_out)
head(ADI_nbh_out)
length(CV2_nbh_out)
head(CV2_nbh_out)

[1] 169

[[1]]
[1] 1.321956

[[2]]
[1] 2.370006

[[3]]
[1] 4.619901

[[4]]
[1] 9.540523

[[5]]
[1] 7.573455

[[6]]
[1] 5.393218

[1] 169

[[1]]
[1] 1.504304

[[2]]
[1] 2.88421

[[3]]
[1] 5.29106

[[4]]
[1] 10.32138

[[5]]
[1] 8.203588

[[6]]
[1] 6.124525

In [ ]:
ADI_CV2_Nbh_out <- do.call(rbind,Map(data.frame,Nbh_row=1:169,ADI=ADI_nbh_out,CV2=CV2_nbh_out))

In [ ]:
# SMOOTH
ADI_CV2_Nbh_out[(ADI_CV2_Nbh_out$ADI<1.32 & ADI_CV2_Nbh_out$CV2<0.49),]

     Nbh_row ADI CV2

In [ ]:
# INTERMITTENT
ADI_CV2_Nbh_out[(ADI_CV2_Nbh_out$ADI>=1.32 & ADI_CV2_Nbh_out$CV2<0.49),]

      Nbh_row ADI CV2
NA    NA      NA  NA
NA.1  NA      NA  NA
NA.2  NA      NA  NA
NA.3  NA      NA  NA
NA.4  NA      NA  NA
NA.5  NA      NA  NA
NA.6  NA      NA  NA
NA.7  NA      NA  NA
NA.8  NA      NA  NA
NA.9  NA      NA  NA
NA.10 NA      NA  NA
NA.11 NA      NA  NA
NA.12 NA      NA  NA
NA.13 NA      NA  NA
NA.14 NA      NA  NA
NA.15 NA      NA  NA
NA.16 NA      NA  NA
NA.17 NA      NA  NA
NA.18 NA      NA  NA
NA.19 NA      NA  NA
NA.20 NA      NA  NA
NA.21 NA      NA  NA
NA.22 NA      NA  NA
NA.23 NA      NA  NA
NA.24 NA      NA  NA
NA.25 NA      NA  NA
NA.26 NA      NA  NA
NA.27 NA      NA  NA
NA.28 NA      NA  NA
NA.29 NA      NA  NA
NA.30 NA      NA  NA
NA.31 NA      NA  NA
NA.32 NA      NA  NA

In [ ]:
# ERRATIC
ADI_CV2_Nbh_out[(ADI_CV2_Nbh_out$ADI<1.32 & ADI_CV2_Nbh_out$CV2>=0.49),]

    Nbh_row ADI      CV2
23   23     1.192946 1.662020
29   29     1.234619 1.906279
30   30     1.253353 2.657881
34   34     1.235129 1.387616
35   35     1.206910 1.783593
39   39     1.154262 1.284335
40   40     1.220707 1.686323
41   41     1.211900 2.293007
56   56     1.206813 2.764604
69   69     1.234721 1.674481
76   76     1.206521 1.696242
77   77     1.142268 2.184117
79   79     1.275380 1.397314
91   91     1.300000 1.811869
162 162     1.170163 2.010068

In [ ]:
# LUMPY
ADI_CV2_Nbh_out[(ADI_CV2_Nbh_out$ADI>=1.32 & ADI_CV2_Nbh_out$CV2>=0.49),]

      Nbh_row ADI        CV2
1      1      1.321956    1.504304
2      2      2.370006    2.884210
3      3      4.619901    5.291060
4      4      9.540523   10.321384
5      5      7.573455    8.203588
6      6      5.393218    6.124525
7      7      1.668899    2.141851
8      8      1.479612    1.989279
9      9      2.239700    4.416411
10    10      3.765743    5.357822
11    11      3.645452    4.719925
12    12      1.753460    1.894245
13    13      2.517259    3.197382
14    14      3.874061    4.621249
15    15      4.113924    4.557398
16    16      1.523179    1.949840
17    17      2.225696    2.432116
18    18      2.960982    3.512489
19    19      1.417062    1.716759
20    20      2.250151    2.802122
21    21      1.340807    1.736007
22    22      1.489934    1.670605
24    24      1.448784    1.909800
25    25      1.324415    1.965774
26    26      1.873199    2.221011
27    27      1.466837    2.802538
28    28      1.426935    1.945768
31    31      1.464538    1.746030
32    32      1.397980    1.666131
33    33      1.592968    2.281367
⋮     ⋮       ⋮          ⋮
NA.17  NA             NA         NA
NA.18  NA             NA         NA
NA.19  NA             NA         NA
NA.20  NA             NA         NA
NA.21  NA             NA         NA
NA.22  NA             NA         NA
NA.23  NA             NA         NA
146   146       5.658592   6.383981
147   147       2.006981   2.378354
148   148      10.936357  14.033026
149   149      14.170616  14.583085
150   150      35.680191  48.929534
151   151      13.615665  15.908056
152   152     132.300885 148.602907
153   153     106.785714 114.621000
154   154      14.628180  16.520593
NA.24  NA             NA         NA
NA.25  NA             NA         NA
NA.26  NA             NA         NA
NA.27  NA             NA         NA
NA.28  NA             NA         NA
NA.29  NA             NA         NA
NA.30  NA             NA         NA
NA.31  NA             NA         NA
NA.32  NA             NA         NA
165   165       2.229014   2.750419
166   166       1.758824   2.289547
167   167       2.762890   4.574981
168   168       3.617227   4.434217
169   169       1.942315   2.101925

In [ ]:
erratic_nbh_out <- ADI_CV2_Nbh_out[(ADI_CV2_Nbh_out$ADI<1.32 & ADI_CV2_Nbh_out$CV2>=0.49),]
erratic_nbh_out[,1]

 [1]  23  29  30  34  35  39  40  41  56  69  76  77  79  91 162

In [ ]:
for (i in erratic_nbh_out[,1]){
  countrow <- sum(divvy_out.tfullh2n[i,2:14951]>0,na.rm=TRUE)
  cat(i,' : ',countrow,'\n')
}

23  :  12532
29  :  12109
30  :  11928
34  :  12104
35  :  12387
39  :  12952
40  :  12247
41  :  12336
56  :  12388
69  :  12108
76  :  12391
77  :  13088
79  :  11722
91  :  11500
162  :  12776

In [ ]:
divvy_out.tfullh2n[77,1:14951]

   Nbh_id 2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
77 28.2   2                   4                   2
   2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
77 0                   0                   0
   2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00 ⋯
77 0                   0                   2                   ⋯
   2018-09-15 14:00:00 2018-09-15 15:00:00 2018-09-15 16:00:00
77 102                 92                  94
   2018-09-15 17:00:00 2018-09-15 18:00:00 2018-09-15 19:00:00
77 84                  86                  84
   2018-09-15 20:00:00 2018-09-15 21:00:00 2018-09-15 22:00:00
77 68                  60                  36
   2018-09-15 23:00:00
77 12

Export

In [ ]:
head(divvy_in.tfullh2n[,1:14951],3)

  Nbh_id 2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
1 1.0    3                   0                   0
2 1.1    0                   0                   2
3 2.0    0                   2                   0
  2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
1 2                   1                   0
2 0                   0                   0
3 0                   0                   0
  2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00 ⋯
1 2                   0                   0                   ⋯
2 0                   0                   0                   ⋯
3 0                   0                   0                   ⋯
  2018-09-15 14:00:00 2018-09-15 15:00:00 2018-09-15 16:00:00
1 21                  22                  32
2  4                   6                  10
3  0                   0                   0
  2018-09-15 17:00:00 2018-09-15 18:00:00 2018-09-15 19:00:00
1 29                  26                  11
2  0                  12                  10
3  2                   2                   0
  2018-09-15 20:00:00 2018-09-15 21:00:00 2018-09-15 22:00:00
1 15                  8                   15
2  4                  0                    2
3  0                  2                    0
  2018-09-15 23:00:00
1 6
2 0
3 2

In [ ]:
write.csv(divvy_in.tfullh2n[,1:14951],"/content/divvy_in.tfullh2n.csv")

In [ ]:
write.csv(divvy_out.tfullh2n[,1:14951],"/content/divvy_out.tfullh2n.csv")

In [ ]:
#table$size1<-ifelse(table$population<500,1,
		ifelse(table$population>=500 & table$population<1000,2,
		ifelse(table$population>=1000 & table$population<2000,3,
		ifelse(table$population>=2000 & table$population<3000,4,5
		))))

In [ ]:
ADI_CV2_Nbh$Forecastability <- ifelse((ADI_CV2_Nbh$ADI<1.32 & ADI_CV2_Nbh$CV2>=0.49),"Erratic","Lumpy")
ADI_CV2_Nbh_out$Forecastability <- ifelse((ADI_CV2_Nbh_out$ADI<1.32 & ADI_CV2_Nbh_out$CV2>=0.49),"Erratic","Lumpy")

In [ ]:
head(ADI_CV2_Nbh)
head(ADI_CV2_Nbh_out)

  Nbh_row ADI      CV2       Forecastability
1 1       1.321956  1.504304 Lumpy
2 2       2.370006  2.884210 Lumpy
3 3       4.619901  5.291060 Lumpy
4 4       9.540523 10.321384 Lumpy
5 5       7.573455  8.203588 Lumpy
6 6       5.393218  6.124525 Lumpy

  Nbh_row ADI      CV2       Forecastability
1 1       1.321956  1.504304 Lumpy
2 2       2.370006  2.884210 Lumpy
3 3       4.619901  5.291060 Lumpy
4 4       9.540523 10.321384 Lumpy
5 5       7.573455  8.203588 Lumpy
6 6       5.393218  6.124525 Lumpy

In [ ]:
divvy_in.tfullh2n[,1]

  [1]  1.0  1.1  2.0  2.1  2.3  2.4  3.0  3.1  3.2  3.3  3.4  3.5  4.0  4.1  4.2
 [16]  4.3  4.4  5.0  5.1  5.2  6.0  6.1  6.2  6.4  6.5  6.6  6.8  7.0  7.1  7.2
 [31]  7.3  7.4  7.5  7.6  8.0  8.1  8.2  8.3  8.4  8.6  8.7 13.1 14.0 14.1 14.3
 [46] 15.0 16.0 16.1 16.2 16.4 17.4 19.1 19.4 20.2 21.0 21.1 22.0 22.1 22.2 22.3
 [61] 23.0 24.0 24.1 24.2 24.4 24.5 24.6 24.7 24.8 25.3 25.4 26.0 27.0 27.1 28.0
 [76] 28.1 28.2 28.3 28.4 28.5 28.7 29.0 29.1 29.2 29.3 30.0 30.2 31.0 31.1 31.2
 [91] 32.0 32.1 32.2 32.3 33.1 33.2 33.3 33.4 34.0 34.1 34.2 35.1 35.2 35.3 35.4
[106] 35.5 35.6 35.7 35.8 36.0 37.0 38.0 39.0 39.1 40.0 41.0 41.1 42.0 42.1 43.0
[121] 43.1 44.0 44.1 44.3 45.0 45.1 45.2 46.0 47.0 48.0 48.1 49.1 49.2 49.3 49.4
[136] 49.5 50.0 50.1 51.0 52.0 53.0 54.1 54.2 54.3 55.0 59.0 60.0 61.0 61.2 67.0
[151] 68.0 68.1 69.0 69.2 71.0 72.0 72.1 72.2 73.0 73.1 74.0 74.1 75.0 75.2 77.0
[166] 77.1 77.2 77.3 77.4

In [ ]:
Nbh_IN_forecastability <- do.call(rbind,Map(data.frame,Nbh_row=1:169,Nbh_id=divvy_in.tfullh2n[,1],
  ADI=ADI_CV2_Nbh$ADI,CV2=ADI_CV2_Nbh$CV2, Forecastability=ADI_CV2_Nbh$Forecastability))

Nbh_OUT_forecastability <- do.call(rbind,Map(data.frame,Nbh_row=1:169,Nbh_id=divvy_out.tfullh2n[,1],
  ADI=ADI_CV2_Nbh_out$ADI,CV2=ADI_CV2_Nbh_out$CV2, Forecastability=ADI_CV2_Nbh_out$Forecastability))

In [ ]:
head(Nbh_IN_forecastability,3)
head(Nbh_OUT_forecastability,3)

  Nbh_row Nbh_id ADI      CV2      Forecastability
1 1       1.0    1.321956 1.504304 Lumpy
2 2       1.1    2.370006 2.884210 Lumpy
3 3       2.0    4.619901 5.291060 Lumpy

  Nbh_row Nbh_id ADI      CV2      Forecastability
1 1       1.0    1.321956 1.504304 Lumpy
2 2       1.1    2.370006 2.884210 Lumpy
3 3       2.0    4.619901 5.291060 Lumpy

In [ ]:
write.csv(Nbh_IN_forecastability,"/content/Nbh_IN_forecastability.csv")

In [ ]:
write.csv(Nbh_OUT_forecastability,"/content/Nbh_OUT_forecastability.csv")

## Neighborhood - Hourly, Aggregated

In [ ]:
nbh_hr_in <- read.csv('/content/Nbh_Hour_IN_1721_full.csv')
nbh_hr_in_res <- read.csv('/content/Nbh_Hour_IN_1721_result.csv')

nbh_hr_out <- read.csv('/content/Nbh_Hour_OUT_1721_full.csv')
nbh_hr_out_res <- read.csv('/content/Nbh_Hour_OUT_1721_result.csv')

In [ ]:
head(nbh_hr_in,2)
dim(nbh_hr_in)
head(nbh_hr_out,2)
dim(nbh_hr_out)

  Hour                X1.0 X1.1 X2.0 X2.1 X2.3 X2.4 X3.0 X3.1 X3.2 ⋯ X73.1
1 2017-01-01 00:00:00 2    0    0    0    0    0    0    2    0    ⋯ 0
2 2017-01-01 01:00:00 0    0    1    0    0    0    0    1    0    ⋯ 0
  X74.0 X74.1 X75.0 X75.2 X77.0 X77.1 X77.2 X77.3 X77.4
1 0     1     0     0     0     0     1     0     0
2 0     1     0     0     0     0     0     0     0

[1] 40914   172

  Hour                X1.0 X1.1 X2.0 X2.1 X2.3 X2.4 X3.0 X3.1 X3.2 ⋯ X73.1
1 2017-01-01 00:00:00 2    0    0    0    0    0    0    0    0    ⋯ 0
2 2017-01-01 01:00:00 1    0    0    0    0    0    0    2    0    ⋯ 0
  X74.0 X74.1 X75.0 X75.2 X77.0 X77.1 X77.2 X77.3 X77.4
1 0     2     0     0     0     0     1     0     1
2 0     2     0     0     0     0     0     0     1

[1] 40914   172

In [ ]:
head(nbh_hr_in_res,2)
dim(nbh_hr_in_res)
head(nbh_hr_out_res,2)
dim(nbh_hr_out_res)

  X stations ADI      CV2      forecastability
1 0 1.0      1.288955 1.473322 Erratic
2 1 1.1      2.114528 2.878125 Lumpy

[1] 171   5

  X stations ADI      CV2      forecastability
1 0 1.0      1.311977 1.519341 Erratic
2 1 1.1      2.098584 2.861429 Lumpy

[1] 171   5

In [ ]:
nbh_hr_in_res$X[nbh_hr_in_res$forecastability=='Erratic']
nbh_hr_out_res$X[nbh_hr_out_res$forecastability=='Erratic']

 [1]   0  22  24  28  29  33  34  38  39  40  56  69  77  78  92  94 163

 [1]   0  22  24  28  29  33  34  38  39  40  56  69  77  78  80  92 163

In [ ]:
unique(nbh_hr_in_res$X)

  [1]   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
 [19]  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
 [37]  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
 [55]  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
 [73]  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
 [91]  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
[109] 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
[127] 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
[145] 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
[163] 162 163 164 165 166 167 168 169 170

In [ ]:
colnames(nbh_hr_in)
length(colnames(nbh_hr_in))

  [1] "Hour"  "X1.0"  "X1.1"  "X2.0"  "X2.1"  "X2.3"  "X2.4"  "X3.0"  "X3.1"
 [10] "X3.2"  "X3.3"  "X3.4"  "X3.5"  "X4.0"  "X4.1"  "X4.2"  "X4.3"  "X4.4"
 [19] "X5.0"  "X5.1"  "X5.2"  "X6.0"  "X6.1"  "X6.2"  "X6.4"  "X6.5"  "X6.6"
 [28] "X6.8"  "X7.0"  "X7.1"  "X7.2"  "X7.3"  "X7.4"  "X7.5"  "X7.6"  "X8.0"
 [37] "X8.1"  "X8.2"  "X8.3"  "X8.4"  "X8.6"  "X8.7"  "X13.1" "X14.0" "X14.1"
 [46] "X14.3" "X15.0" "X16.0" "X16.1" "X16.2" "X16.3" "X16.4" "X17.4" "X19.1"
 [55] "X19.4" "X20.2" "X21.0" "X21.1" "X22.0" "X22.1" "X22.2" "X22.3" "X23.0"
 [64] "X24.0" "X24.1" "X24.2" "X24.4" "X24.5" "X24.6" "X24.7" "X24.8" "X25.3"
 [73] "X25.4" "X25.5" "X26.0" "X27.0" "X27.1" "X28.0" "X28.1" "X28.2" "X28.3"
 [82] "X28.4" "X28.5" "X28.7" "X29.0" "X29.1" "X29.2" "X29.3" "X30.0" "X30.2"
 [91] "X31.0" "X31.1" "X31.2" "X32.0" "X32.1" "X32.2" "X32.3" "X33.1" "X33.2"
[100] "X33.3" "X33.4" "X34.0" "X34.1" "X34.2" "X35.1" "X35.2" "X35.3" "X35.4"
[109] "X35.5" "X35.6" "X35.7" "X35.8" "X36.0" "X37.0" "X38.0" "X39.0" "X39.1"
[118] "X40.0" "X41.0" "X41.1" "X42.0" "X42.1" "X43.0" "X43.1" "X44.0" "X44.1"
[127] "X44.3" "X45.0" "X45.1" "X45.2" "X46.0" "X47.0" "X48.0" "X48.1" "X49.1"
[136] "X49.2" "X49.3" "X49.4" "X49.5" "X50.0" "X50.1" "X51.0" "X52.0" "X53.0"
[145] "X54.1" "X54.2" "X54.3" "X55.0" "X59.0" "X60.0" "X61.0" "X61.2" "X67.0"
[154] "X68.0" "X68.1" "X69.0" "X69.2" "X71.0" "X72.0" "X72.1" "X72.2" "X73.0"
[163] "X73.1" "X74.0" "X74.1" "X75.0" "X75.2" "X77.0" "X77.1" "X77.2" "X77.3"
[172] "X77.4"

[1] 172

In [ ]:
# TRANSPOSE

# first remember the names
hour_in <- nbh_hr_in$Hour
hour_out <- nbh_hr_out$Hour

# transpose all but the first column (name)
nbh_hr_in_t <- as.data.frame(t(nbh_hr_in[,-1]))
colnames(nbh_hr_in_t) <- hour_in
head(nbh_hr_in_t)

nbh_hr_out_t <- as.data.frame(t(nbh_hr_out[,-1]))
colnames(nbh_hr_out_t) <- hour_out
head(nbh_hr_out_t)

     2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
X1.0 2                   0                   0
X1.1 0                   0                   1
X2.0 0                   1                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
X1.0 1                   1                   0
X1.1 0                   0                   0
X2.0 0                   0                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00
X1.0 1                   0                   0
X1.1 0                   0                   0
X2.0 0                   0                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2017-01-01 09:00:00 ⋯ 2021-09-01 08:00:00 2021-09-01 09:00:00
X1.0 3                   ⋯ 0                   0
X1.1 0                   ⋯ 0                   0
X2.0 0                   ⋯ 0                   0
X2.1 0                   ⋯ 0                   0
X2.3 0                   ⋯ 0                   0
X2.4 0                   ⋯ 0                   0
     2021-09-01 10:00:00 2021-09-01 11:00:00 2021-09-01 12:00:00
X1.0 0                   0                   0
X1.1 0                   0                   0
X2.0 0                   0                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2021-09-01 13:00:00 2021-09-01 14:00:00 2021-09-01 15:00:00
X1.0 0                   0                   0
X1.1 0                   0                   0
X2.0 0                   0                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2021-09-01 16:00:00 2021-09-01 17:00:00
X1.0 0                   0
X1.1 0                   0
X2.0 0                   0
X2.1 0                   0
X2.3 0                   0
X2.4 0                   0

     2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
X1.0 2                   1                   0
X1.1 0                   0                   2
X2.0 0                   0                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
X1.0 0                   0                   0
X1.1 0                   0                   0
X2.0 0                   0                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00
X1.0 0                   0                   0
X1.1 0                   0                   0
X2.0 0                   0                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2017-01-01 09:00:00 ⋯ 2021-09-01 08:00:00 2021-09-01 09:00:00
X1.0 2                   ⋯ 0                   0
X1.1 0                   ⋯ 0                   0
X2.0 1                   ⋯ 0                   0
X2.1 0                   ⋯ 0                   0
X2.3 0                   ⋯ 0                   0
X2.4 0                   ⋯ 0                   0
     2021-09-01 10:00:00 2021-09-01 11:00:00 2021-09-01 12:00:00
X1.0 0                   0                   0
X1.1 0                   0                   0
X2.0 0                   0                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2021-09-01 13:00:00 2021-09-01 14:00:00 2021-09-01 15:00:00
X1.0 0                   0                   0
X1.1 0                   0                   0
X2.0 0                   0                   0
X2.1 0                   0                   0
X2.3 0                   0                   0
X2.4 0                   0                   0
     2021-09-01 16:00:00 2021-09-01 17:00:00
X1.0 0                   0
X1.1 0                   0
X2.0 0                   0
X2.1 0                   0
X2.3 0                   0
X2.4 0                   0

In [ ]:
(nbh_hr_in_res$X[nbh_hr_in_res$forecastability=='Erratic']+1)

 [1]   1  23  25  29  30  34  35  39  40  41  57  70  78  79  93  95 164

In [ ]:
nbh_hr_in_erratic <- nbh_hr_in_t[(nbh_hr_in_res$X[nbh_hr_in_res$forecastability=='Erratic']+1),]
head(nbh_hr_in_erratic)

     2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
X1.0 2                   0                   0
X6.2 0                   2                   4
X6.5 1                   0                   0
X7.1 4                   0                   1
X7.2 3                   1                   0
X7.6 0                   2                   1
     2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
X1.0 1                   1                   0
X6.2 0                   0                   0
X6.5 0                   0                   0
X7.1 0                   0                   0
X7.2 1                   0                   0
X7.6 2                   0                   0
     2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00
X1.0 1                   0                   0
X6.2 1                   0                   0
X6.5 0                   0                   1
X7.1 0                   0                   3
X7.2 2                   1                   0
X7.6 0                   1                   2
     2017-01-01 09:00:00 ⋯ 2021-09-01 08:00:00 2021-09-01 09:00:00
X1.0 3                   ⋯ 0                   0
X6.2 1                   ⋯ 0                   0
X6.5 3                   ⋯ 0                   0
X7.1 2                   ⋯ 0                   0
X7.2 2                   ⋯ 1                   0
X7.6 1                   ⋯ 0                   0
     2021-09-01 10:00:00 2021-09-01 11:00:00 2021-09-01 12:00:00
X1.0 0                   0                   0
X6.2 0                   0                   0
X6.5 0                   0                   0
X7.1 0                   0                   0
X7.2 0                   0                   0
X7.6 0                   0                   0
     2021-09-01 13:00:00 2021-09-01 14:00:00 2021-09-01 15:00:00
X1.0 0                   0                   0
X6.2 0                   0                   0
X6.5 0                   0                   0
X7.1 0                   0                   0
X7.2 0                   0                   0
X7.6 0                   0                   0
     2021-09-01 16:00:00 2021-09-01 17:00:00
X1.0 0                   0
X6.2 0                   0
X6.5 0                   0
X7.1 0                   0
X7.2 0                   0
X7.6 0                   0

In [ ]:
(nbh_hr_out_res$X[nbh_hr_out_res$forecastability=='Erratic']+1)

 [1]   1  23  25  29  30  34  35  39  40  41  57  70  78  79  81  93 164

In [ ]:
nbh_hr_out_erratic <- nbh_hr_out_t[(nbh_hr_out_res$X[nbh_hr_out_res$forecastability=='Erratic']+1),]
head(nbh_hr_out_erratic)

     2017-01-01 00:00:00 2017-01-01 01:00:00 2017-01-01 02:00:00
X1.0 2                   1                   0
X6.2 0                   2                   0
X6.5 0                   1                   0
X7.1 2                   0                   0
X7.2 1                   1                   4
X7.6 2                   1                   1
     2017-01-01 03:00:00 2017-01-01 04:00:00 2017-01-01 05:00:00
X1.0 0                   0                   0
X6.2 0                   0                   0
X6.5 0                   0                   0
X7.1 2                   0                   0
X7.2 0                   0                   0
X7.6 3                   0                   0
     2017-01-01 06:00:00 2017-01-01 07:00:00 2017-01-01 08:00:00
X1.0 0                   0                   0
X6.2 0                   1                   1
X6.5 1                   0                   0
X7.1 0                   1                   1
X7.2 0                   1                   1
X7.6 1                   1                   0
     2017-01-01 09:00:00 ⋯ 2021-09-01 08:00:00 2021-09-01 09:00:00
X1.0 2                   ⋯ 0                   0
X6.2 1                   ⋯ 0                   0
X6.5 0                   ⋯ 0                   0
X7.1 2                   ⋯ 0                   0
X7.2 4                   ⋯ 0                   0
X7.6 0                   ⋯ 0                   0
     2021-09-01 10:00:00 2021-09-01 11:00:00 2021-09-01 12:00:00
X1.0 0                   0                   0
X6.2 0                   0                   0
X6.5 0                   0                   0
X7.1 0                   0                   0
X7.2 0                   0                   0
X7.6 0                   0                   0
     2021-09-01 13:00:00 2021-09-01 14:00:00 2021-09-01 15:00:00
X1.0 0                   0                   0
X6.2 0                   0                   0
X6.5 0                   0                   0
X7.1 0                   0                   0
X7.2 0                   0                   0
X7.6 0                   0                   0
     2021-09-01 16:00:00 2021-09-01 17:00:00
X1.0 0                   0
X6.2 0                   0
X6.5 0                   0
X7.1 0                   0
X7.2 0                   0
X7.6 0                   0

In [ ]:
nbh_hr_in_erratic_sum <- data.frame(colSums(nbh_hr_in_erratic))
colnames(nbh_hr_in_erratic_sum) <- 'bike_in'
head(nbh_hr_in_erratic_sum)

                    bike_in
2017-01-01 00:00:00 19
2017-01-01 01:00:00 15
2017-01-01 02:00:00 22
2017-01-01 03:00:00 10
2017-01-01 04:00:00  2
2017-01-01 05:00:00  0

In [ ]:
nbh_hr_out_erratic_sum <- data.frame(colSums(nbh_hr_out_erratic))
colnames(nbh_hr_out_erratic_sum) <- 'bike_out'
head(nbh_hr_out_erratic_sum)

                    bike_out
2017-01-01 00:00:00 24
2017-01-01 01:00:00 19
2017-01-01 02:00:00 19
2017-01-01 03:00:00  7
2017-01-01 04:00:00  2
2017-01-01 05:00:00  1

In [ ]:
print('ADI for Neighborhood Hourly Bike-In, Erratic Aggregated:' )
sum(nbh_hr_in_erratic_sum$bike_in>=0,na.rm=TRUE)/sum(nbh_hr_in_erratic_sum$bike_in>0,na.rm=TRUE)
print('CV2 for Neighborhood Hourly Bike-In, Erratic Aggregated:' )
(sd(nbh_hr_in_erratic_sum$bike_in)/mean(nbh_hr_in_erratic_sum$bike_in))^2

print('ADI for Neighborhood Hourly Bike-Out, Erratic Aggregated:' )
sum(nbh_hr_out_erratic_sum$bike_out>=0,na.rm=TRUE)/sum(nbh_hr_out_erratic_sum$bike_out>0,na.rm=TRUE)
print('CV2 for Neighborhood Hourly Bike-Out, Erratic Aggregated:' )
(sd(nbh_hr_out_erratic_sum$bike_out)/mean(nbh_hr_out_erratic_sum$bike_out))^2

[1] "ADI for Neighborhood Hourly Bike-In, Erratic Aggregated:"

[1] 1.011196

[1] "CV2 for Neighborhood Hourly Bike-In, Erratic Aggregated:"

[1] 1.382553

[1] "ADI for Neighborhood Hourly Bike-Out, Erratic Aggregated:"

[1] 1.012572

[1] "CV2 for Neighborhood Hourly Bike-Out, Erratic Aggregated:"

[1] 1.487564

In [ ]:
nbh_hr_in_sum <- data.frame(colSums(nbh_hr_in_t))
colnames(nbh_hr_in_sum) <- 'bike_in'
head(nbh_hr_in_sum)

                    bike_in
2017-01-01 00:00:00 34
2017-01-01 01:00:00 42
2017-01-01 02:00:00 43
2017-01-01 03:00:00 22
2017-01-01 04:00:00  7
2017-01-01 05:00:00  1

In [ ]:
nbh_hr_out_sum <- data.frame(colSums(nbh_hr_out_t))
colnames(nbh_hr_out_sum) <- 'bike_out'
head(nbh_hr_out_sum)

                    bike_out
2017-01-01 00:00:00 33
2017-01-01 01:00:00 46
2017-01-01 02:00:00 36
2017-01-01 03:00:00 18
2017-01-01 04:00:00  6
2017-01-01 05:00:00  4

In [ ]:
print('ADI for Neighborhood Hourly Bike-In, All Aggregated:' )
sum(nbh_hr_in_sum$bike_in>=0,na.rm=TRUE)/sum(nbh_hr_in_sum$bike_in>0,na.rm=TRUE)
print('CV2 for Neighborhood Hourly Bike-In, All Aggregated:' )
(sd(nbh_hr_in_sum$bike_in)/mean(nbh_hr_in_sum$bike_in))^2

print('ADI for Neighborhood Hourly Bike-Out, All Aggregated:' )
sum(nbh_hr_out_sum$bike_out>=0,na.rm=TRUE)/sum(nbh_hr_out_sum$bike_out>0,na.rm=TRUE)
print('CV2 for Neighborhood Hourly Bike-Out, All Aggregated:' )
(sd(nbh_hr_out_sum$bike_out)/mean(nbh_hr_out_sum$bike_out))^2

[1] "ADI for Neighborhood Hourly Bike-In, All Aggregated:"

[1] 1.004567

[1] "CV2 for Neighborhood Hourly Bike-In, All Aggregated:"

[1] 1.384251

[1] "ADI for Neighborhood Hourly Bike-Out, All Aggregated:"

[1] 1.005332

[1] "CV2 for Neighborhood Hourly Bike-Out, All Aggregated:"

[1] 1.399947

In [ ]:
nbh_hr_in_erratic_sum <- cbind(hour=rownames(nbh_hr_in_erratic_sum),nbh_hr_in_erratic_sum)
rownames(nbh_hr_in_erratic_sum) <- NULL
head(nbh_hr_in_erratic_sum)

  hour                bike_in
1 2017-01-01 00:00:00 19
2 2017-01-01 01:00:00 15
3 2017-01-01 02:00:00 22
4 2017-01-01 03:00:00 10
5 2017-01-01 04:00:00  2
6 2017-01-01 05:00:00  0

In [ ]:
nbh_hr_out_erratic_sum <- cbind(hour=rownames(nbh_hr_out_erratic_sum),nbh_hr_out_erratic_sum)
rownames(nbh_hr_out_erratic_sum) <- NULL
head(nbh_hr_out_erratic_sum)

  hour                bike_out
1 2017-01-01 00:00:00 24
2 2017-01-01 01:00:00 19
3 2017-01-01 02:00:00 19
4 2017-01-01 03:00:00  7
5 2017-01-01 04:00:00  2
6 2017-01-01 05:00:00  1

In [ ]:
nbh_hr_in_sum <- cbind(hour=rownames(nbh_hr_in_sum),nbh_hr_in_sum)
rownames(nbh_hr_in_sum) <- NULL
head(nbh_hr_in_sum)

  hour                bike_in
1 2017-01-01 00:00:00 34
2 2017-01-01 01:00:00 42
3 2017-01-01 02:00:00 43
4 2017-01-01 03:00:00 22
5 2017-01-01 04:00:00  7
6 2017-01-01 05:00:00  1

In [ ]:
nbh_hr_out_sum <- cbind(hour=rownames(nbh_hr_out_sum),nbh_hr_out_sum)
rownames(nbh_hr_out_sum) <- NULL
head(nbh_hr_out_sum)

  hour                bike_out
1 2017-01-01 00:00:00 33
2 2017-01-01 01:00:00 46
3 2017-01-01 02:00:00 36
4 2017-01-01 03:00:00 18
5 2017-01-01 04:00:00  6
6 2017-01-01 05:00:00  4

In [ ]:
nbh_hr_in_erratic_sum_1719 <- nbh_hr_in_erratic_sum[ ((format(strptime(nbh_hr_in_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2017') |
                              (format(strptime(nbh_hr_in_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2018') |
                              (format(strptime(nbh_hr_in_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2019')),]
nbh_hr_in_erratic_sum_2021 <- nbh_hr_in_erratic_sum[ ((format(strptime(nbh_hr_in_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2020') |
                              (format(strptime(nbh_hr_in_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2021')),]
nbh_hr_out_erratic_sum_1719 <- nbh_hr_out_erratic_sum[ ((format(strptime(nbh_hr_out_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2017') |
                              (format(strptime(nbh_hr_out_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2018') |
                              (format(strptime(nbh_hr_out_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2019')),]
nbh_hr_out_erratic_sum_2021 <- nbh_hr_out_erratic_sum[ ((format(strptime(nbh_hr_out_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2020') |
                              (format(strptime(nbh_hr_out_erratic_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2021')),]
nbh_hr_in_sum_1719 <- nbh_hr_in_sum[ ((format(strptime(nbh_hr_in_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2017') |
                              (format(strptime(nbh_hr_in_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2018') |
                              (format(strptime(nbh_hr_in_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2019')),]
nbh_hr_in_sum_2021 <- nbh_hr_in_sum[ ((format(strptime(nbh_hr_in_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2020') |
                              (format(strptime(nbh_hr_in_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2021')),]
nbh_hr_out_sum_1719 <- nbh_hr_out_sum[ ((format(strptime(nbh_hr_out_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2017') |
                              (format(strptime(nbh_hr_out_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2018') |
                              (format(strptime(nbh_hr_out_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2019')),]
nbh_hr_out_sum_2021 <- nbh_hr_out_sum[ ((format(strptime(nbh_hr_out_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2020') |
                              (format(strptime(nbh_hr_out_sum$hour, 
                              format = '%Y-%m-%d %H:%M:%S'),'%Y')=='2021')),]

In [ ]:
print('ADI for Neighborhood Hourly Bike-In, All Aggregated 2017-2019:' )
sum(nbh_hr_in_sum_1719$bike_in>=0,na.rm=TRUE)/sum(nbh_hr_in_sum_1719$bike_in>0,na.rm=TRUE)
print('CV2 for Neighborhood Hourly Bike-In, All Aggregated 2017-2019:' )
(sd(nbh_hr_in_sum_1719$bike_in)/mean(nbh_hr_in_sum_1719$bike_in))^2
print('ADI for Neighborhood Hourly Bike-Out, All Aggregated 2017-2019:' )
sum(nbh_hr_out_sum_1719$bike_out>=0,na.rm=TRUE)/sum(nbh_hr_out_sum_1719$bike_out>0,na.rm=TRUE)
print('CV2 for Neighborhood Hourly Bike-Out, All Aggregated 2017-2019:' )
(sd(nbh_hr_out_sum_1719$bike_out)/mean(nbh_hr_out_sum_1719$bike_out))^2

print('ADI for Neighborhood Hourly Bike-In, All Aggregated 2020-2021:' )
sum(nbh_hr_in_sum_2021$bike_in>=0,na.rm=TRUE)/sum(nbh_hr_in_sum_2021$bike_in>0,na.rm=TRUE)
print('CV2 for Neighborhood Hourly Bike-In, All Aggregated 2020-2021:' )
(sd(nbh_hr_in_sum_2021$bike_in)/mean(nbh_hr_in_sum_2021$bike_in))^2
print('ADI for Neighborhood Hourly Bike-Out, All Aggregated 2017-2019:' )
sum(nbh_hr_out_sum_2021$bike_out>=0,na.rm=TRUE)/sum(nbh_hr_out_sum_2021$bike_out>0,na.rm=TRUE)
print('CV2 for Neighborhood Hourly Bike-Out, All Aggregated 2017-2019:' )
(sd(nbh_hr_out_sum_2021$bike_out)/mean(nbh_hr_out_sum_2021$bike_out))^2

[1] "ADI for Neighborhood Hourly Bike-In, All Aggregated 2017-2019:"

[1] 1.001677

[1] "CV2 for Neighborhood Hourly Bike-In, All Aggregated 2017-2019:"

[1] 1.346488

[1] "ADI for Neighborhood Hourly Bike-Out, All Aggregated 2017-2019:"

[1] 1.002097

[1] "CV2 for Neighborhood Hourly Bike-Out, All Aggregated 2017-2019:"

[1] 1.359951

[1] "ADI for Neighborhood Hourly Bike-In, All Aggregated 2020-2021:"

[1] 1.009799

[1] "CV2 for Neighborhood Hourly Bike-In, All Aggregated 2020-2021:"

[1] 1.440839

[1] "ADI for Neighborhood Hourly Bike-Out, All Aggregated 2017-2019:"

[1] 1.011194

[1] "CV2 for Neighborhood Hourly Bike-Out, All Aggregated 2017-2019:"

[1] 1.458634

### Mapping the Initial Clusters

In [ ]:
init_cluster <- read.csv('divvy_inout_cluster.csv')

In [ ]:
head(init_cluster)
dim(init_cluster)

  X                         clusterIn clusterOut clusterDiff
1 Keeler.Ave...Roosevelt.Rd 1         1          0
2 East.End.Ave...87th.St    1         1          0
3 NA.                       2         2          0
4 Greenwood.Ave...91st.St   1         1          0
5 Big.Marsh.Park            1         1          0
6 Kildare.Ave...26th.St     1         1          0

[1] 845   4

In [ ]:
comm <- read.csv('Divvy_stations_community.csv')

In [ ]:
head(comm,2)
dim(comm)

  X station_id lng       lat      cord
1 0 2          -87.62053 41.87650 (-87.62052684219132, 41.87650284189418)
2 1 3          -87.61537 41.86722 (-87.61537258521274, 41.86721537439574)
  station_name        Nbh_id com_id Docks.in.Service
1 Buckingham Fountain 32.0   32     39
2 Shedd Aquarium      33.3   33     55

[1] 1361    9

In [ ]:
library(stringr)
comm$station_name1 <- str_replace_all(comm$station_name,' ','.')
comm$station_name1 <- str_replace_all(comm$station_name1,'&','.')
head(comm$station_name1)

[1] "Buckingham.Fountain"         "Shedd.Aquarium"
[3] "Burnham.Harbor"              "State.St...Harrison.St"
[5] "Dusable.Harbor"              "Field.Blvd...South.Water.St"

In [ ]:
colnames(init_cluster)[1] <- 'station_name1'
head(init_cluster,2)

  station_name1             clusterIn clusterOut clusterDiff
1 Keeler.Ave...Roosevelt.Rd 1         1          0
2 East.End.Ave...87th.St    1         1          0

In [ ]:
init_cluster_ll <- merge(init_cluster,comm[,c('lng','lat','station_name1')],by = 'station_name1')

In [ ]:
head(init_cluster_ll,2)
dim(init_cluster_ll)

  station_name1              clusterIn clusterOut clusterDiff lng      lat
1 Aberdeen.St...Jackson.Blvd 1         1          0           -87.6548 41.87773
2 Aberdeen.St...Jackson.Blvd 1         1          0           -87.6548 41.87772

[1] 1302    6

In [ ]:
?merge

In [ ]:
init_cluster_ll <- init_cluster_ll[!duplicated(init_cluster_ll$station_name1),]
dim(init_cluster_ll)

[1] 730   6

In [ ]:
init_cluster_ll_in <- init_cluster_ll[,c('station_name1','clusterIn','lng','lat')]
dim(init_cluster_ll_in)
colnames(init_cluster_ll_in)
init_cluster_ll_out <- init_cluster_ll[,c('station_name1','clusterOut','lng','lat')]
dim(init_cluster_ll_out)
colnames(init_cluster_ll_out)

[1] 730   4

[1] "station_name1" "clusterIn"     "lng"           "lat"

[1] 730   4

[1] "station_name1" "clusterOut"    "lng"           "lat"

In [ ]:
write.csv(init_cluster_ll,"/content/init_cluster_ll.csv")